export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ORDER_INIT = 'ORDER_INIT';
export const ORDER_START = 'ORDER_START';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILURE = 'ORDER_FAILURE';

export const INIT_ADDINS = 'INIT_ADDINS';
export const ADD_ADDITIVE = 'ADD_ADDITIVE';
export const REMOVE_ADDITIVE = 'REMOVE_ADDITIVE';
export const FETCH_ADDINS_FAILURE = 'FETCH_ADDINS_FAILURE';

export const ORDERS_INIT = 'ORDERS_INIT';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAILURE = 'ORDERS_FAILURE';
